site_name: Clams Docs
theme:
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: clams
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github
    admonition:
      info: octicons/info-16
      tip: octicons/squirrel-16
  logo: assets/logo.png
  favicon: assets/favicon.png
  features:
    - navigation.instant
    - navigation.tracking
repo_url: https://github.com/clams-tech/docs
repo_name: clams-tech/docs
edit_uri: edit/main/docs/
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/clamstech
    - icon: fontawesome/brands/discord
      link: https://discord.gg/F2SK8QGW
    - icon: fontawesome/brands/github
      link: https://github.com/clams-tech
markdown_extensions:
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
nav:
  - "index.md"
  - "connection.md"
  - "authentication.md"
  - "installation.md"
  - "encryption.md"
  - "roadmap.md"
  - "project-goals.md"
  - "running-a-vpn.md"
  - "testing-locally.md"
  - "BOLT12-offers.md"
extra_css:
  - stylesheets/extra.css
