site_name: Clams Docs
theme:
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github
  logo: assets/logo.png
  favicon: assets/favicon.ico
  features:
    - navigation.instant
    - navigation.tracking
repo_url: https://github.com/clams-tech/docs
repo_name: clams-tech/docs
edit_uri: edit/main/docs/
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/clamstech
    - icon: fontawesome/brands/discord
      link: https://discord.gg/F2SK8QGW
    - icon: fontawesome/brands/github
      link: https://github.com/clams-tech
